"""Add first_dose column to Medication

Revision ID: 034925cf9084
Revises: b11b348d1b3d
Create Date: 2024-04-19 10:01:59.349238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034925cf9084'
down_revision = 'b11b348d1b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_dose', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_column('first_dose')

    # ### end Alembic commands ###
