"""Add is_stopped column to Medication

Revision ID: b11b348d1b3d
Revises: 327db84a1d89
Create Date: 2024-04-19 09:21:35.677449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11b348d1b3d'
down_revision = '327db84a1d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_stopped', sa.Boolean(), nullable=False))
        batch_op.alter_column('frequency',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_menstruation', sa.Boolean(), nullable=False))
        batch_op.drop_column('menstruation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menstruation', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('has_menstruation')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('is_stopped')

    # ### end Alembic commands ###
