# This workflow will install Python dependencies, run tests and lint with a single version of Python
# Adapted from https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - dev
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
      fail-fast: true
    steps:
      # Checkout the code
      - uses: actions/checkout@v4

        # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # Caches the installed Python packages

        # Install Python dependencies for API
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
        working-directory: "api"

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 api/ --count --select=E9,F63,F7,F82 --show-source --statistics

          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 api/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
